// Rubylike.js (https://github.com/ksss/Rubylike.js)
// Copyright (c) 2012 ksss <co000ri@gmail.com>
(function(){var d=function(a){if("function"!==typeof a)throw new TypeError("arguments must be a function");d.define();a=a(d);d.remove();return a},i=function(a){if(null===a)return"nil";if(void 0===a)return"undefined";switch(Object.prototype.toString.call(a)){case "[object Number]":return"Number"}var b=/^\s*function\s*([^\(]*)[\S\s]+$/im;return"function"===typeof a?(a+"").replace(b,"$1"):(a.constructor+"").replace(b,"$1")},j=function(a,b){void 0===d[i(a)]._methods&&(d[i(a)]._methods=[]);a["new"]=b["new"];
for(var c in b.prototype)b.prototype.hasOwnProperty(c)&&(d[i(a)]._methods.push(c),"function"===typeof a.prototype[c]&&"Hash"!==i(a)&&(a.prototype["_"+c]=a.prototype[c],d[i(a)]._methods.push("_"+c)),a.prototype[c]=b.prototype[c])},l=function(a){var b=h.Array.sort.call(d[i(a)]._methods).reverse();d[i(a)]._methods=[];delete a["new"];for(var c=0,e=b.length;c<e;c+=1){var f=b[c];/^_/.test(f)&&"_methods"!==f&&(a.prototype[f.substr(1,f.length-1)]=a.prototype[f]);delete a.prototype[f]}};d.version="0.0.0";
d.is_defined=!1;d.define=function(){nil=null;Hash=d.Hash;j(Object,d.Object);j(Array,d.Array);j(Hash,d.Hash);j(String,d.String);j(Number,d.Number);d.is_defined=!0};d.remove=function(){l(Object);l(Array);l(String);l(Number);delete Hash;delete nil;d.is_defined=!1};d.raise=function(a,b){var c=Error();c.name=a;c.message=b;throw c;};var h={Array:{pop:Array.prototype.pop,push:Array.prototype.push,reverse:Array.prototype.reverse,shift:Array.prototype.shift,sort:Array.prototype.sort,splice:Array.prototype.splice,
unshift:Array.prototype.unshift,concat:Array.prototype.concat,join:Array.prototype.join,slice:Array.prototype.slice,map:Array.prototype.map,every:Array.prototype.every}};d.Object=function(){};d.Object["new"]=function(){return new d.Object};d.Object.prototype={"class":function(){if(null===this)return"nil";if(void 0===this)return"undefined";var a=this.constructor;return"function"===typeof a?(""+a).replace(/^\s*function\s*([^\(]*)[\S\s]+$/im,"$1"):a},eql:function(a){var b,c;if(this===a)return!0;if(this.prototype!==
a.prototype)return!1;if(this.valueOf()===a.valueOf())return!0;if(this instanceof Date&&a instanceof Date)return this.getTime()===a.getTime();if("object"!=typeof this&&"object"!=typeof a)return this===a;try{c=Object.keys(this),b=Object.keys(a)}catch(d){return!1}if(c.length!==b.length)return!1;h.Array.sort.call(c);h.Array.sort.call(b);for(var f=0,g=c.length;f<g;f+=1)if(c[f]!==b[f])return!1;for(f=c.length-1;0<=f;f--)if(b=c[f],!arguments.callee.call(this[b],a[b]))return!1;return!0},methods:function(){return d[this["class"]()]._methods}};
d.Array=function(){this.length=0};d.Array["new"]=function(a,b){var c=d.is_defined?[]:new d.Array;if(0===arguments.length)return c;switch(i(a)){case "Number":void 0===b&&(b=null);for(var e=0;e<a;e+=1)h.Array.push.call(c,b);break;case "Array":c.concat(a);break;case "undefined":break;case "nil":d.raise("TypeError","`initialize': no implicit conversion from nil to integer");break;default:d.raise("TypeError","`initialize': can't convert "+i(a)+" into Integer")}return c};d.Array.prototype=[];d.Array.def=
function(a){for(name in a)a.hasOwnProperty(name)&&(d.Array.prototype[name]=a[name])};d.Array.def({methods:function(){return Object.keys(d.Array.prototype)},all:function(a){if("function"===typeof a)for(var b=0,c=this.length;b<c;b+=1){if(!a(this[b]))return!1}else{b=0;for(c=this.length;b<c;b+=1)if(!this[b])return!1}return!0},any:function(a){if("function"===typeof a)for(var b=0,c=this.length;b<c;b+=1){if(a(this[b]))return!0}else{b=0;for(c=this.length;b<c;b+=1)if(this[b])return!0}return!1},assoc:function(a){for(var b=
0,c=this.length;b<c;b+=1){var e=this[b];if(d.Object.prototype.eql.call(e[0],a))return e}return null},at:function(a){try{a=d.Number.prototype.to_int.call(a)}catch(b){d.raise("TypeError","`at': can't convert "+i(a)+" into Integer")}0>a&&(a+=this.length);a=this[a];return void 0===a?null:a},clear:function(){h.Array.splice.call(this,0,this.length);return this},clone:function(){return d.Array["new"]().concat(this)},collect:function(a){var b=d.Array["new"]();if("function"===typeof h.Array.map)return b.concat(h.Array.map.call(this,
a));for(var c=0,e=this.length;c<e;c+=1)h.Array.push.call(b,a(this[c]));return b},combination:function(a,b){(0===arguments.length||2<arguments.length)&&d.raise("TypeError","`combination': wrong number of arguments ("+arguments.length+" for 1)");"number"!==typeof a&&d.raise("TypeError","`combination': can't convert "+i(a)+" into Integer");var c;a:{c=d.Array["new"]();var e=this.length;if(!(0>a||e<a))if(0===a)c.push(d.Array["new"]());else if(1===a)for(var f=0;f<e;f+=1)h.Array.push.call(c,d.Array["new"]([this[f]]));
else{for(var g=0,k=[],m=[],f=0;f<a+1;f+=1)m.push(0);for(m[0]=-1;;){k[g]=this[m[g+1]];for(g++;g<a;g++)m[g+1]=m[g]+1,k[g]=this[m[g+1]];h.Array.push.call(c,d.Array["new"](k));do{if(0===g)break a;m[g--]++}while(m[g+1]+a===e+g+1)}}}if("function"===typeof b){e=0;for(f=c.length;e<f;e+=1)b(c[e]);return this}return c},compact:function(){return this.reject(function(a){return null===a})},concat:function(a){"Array"!==i(a)&&d.raise("TypeError","`concat': can't convert "+i(a)+" into Array");"function"===typeof a.to_a?
h.Array.push.apply(this,a.to_a()):h.Array.push.apply(this,a);return this},reject:function(a){for(var b=d.Array["new"](),c=0,e=this.length;c<e;c+=1)a(this[c])||h.Array.push.call(b,this[c]);return b.length===this.length?null:b},delete_if:function(a){for(var b=0,c=this.length;b<c;b+=1)a(this[b])&&h.Array.splice.call(this,b,1);return this},count:function(){var a=0,b,c;if(0===arguments.length)return"function"===typeof this.size?this.size():this.length;if("function"===typeof arguments[0])for(b=0;c=this[b];b+=
1)arguments[0](c)&&a++;else for(b=0;c=this[b];b+=1)arguments[0]===c&&a++;return a},cycle:function(a,b){if(2!==arguments.length)d.raise("TypeError","`cycle': wrong number of arguments ("+arguments.length+" for 2)");else for(var c=0,e=this.length;c<a;c+=1)b(this[c%e]);return null},"delete":function(a,b){var c,d=this.length,f=[];if("function"===typeof b)for(c=0;c<d;c+=1)this[c]===a?f.push(c):b(this[c]);else for(c=0;c<d;c+=1)this[c]===a&&f.push(c);for(c=f.length;c--;)h.Array.splice.call(this,f[c],1);
return d!==this.length?a:null},delete_at:function(a){0>a&&(a+=this.length);var b=this.at(a);null!==b&&h.Array.splice.call(this,a,1);return b},drop:function(a){var b=this.clone();h.Array.splice.call(b,0,a);return b},drop_while:function(a){for(var b=this.clone(),c=0,d=b.length;c<d&&a(b[c]);c+=1);h.Array.splice.call(b,0,c);return b},each:function(a){for(var b=0,c=this.length;b<c;b+=1)a(this[b]);return this},each_cons:function(a,b){for(var c=0,e=this.length-a+1;c<e;c+=1){var f=d.Array["new"]();b(f.concat(h.Array.slice.call(this,
c,c+a)))}return null},each_slice:function(a,b){for(var c=0,e=this.length;c<e;c+=a)b(d.Array["new"](h.Array.slice.call(this,c,c+a)));return null},each_index:function(a){for(var b=0,c=this.length;b<c;b+=1)a(b);return this},each_with_index:function(a){for(var b=0,c=this.length;b<c;b+=1)a(this[b],b);return this},each_with_object:function(a,b){for(var c=0,d=this.length;c<d;c+=1)b(this[c],a);return a},eql:function(a){return d.Object.prototype.eql.call(this,a)},fetch:function(a,b){0===arguments.length&&
d.raise("TypeError","`fetch': wrong number of arguments ("+arguments.length+" for 1..2)");var c=this.at(a);if(null===c){if(1===arguments.length)throw Error("`fetch': index "+a+" outside of array bounds: -"+this.length+"..."+this.length);return"function"===typeof b?b(a):b}return c},fill:function(){var a,b,c;if(1===arguments.length)if("function"===typeof arguments[0]){a=0;for(c=this.length;a<c;a+=1)this[a]=arguments[0](a)}else{a=0;for(c=this.length;a<c;a+=1)this[a]=arguments[0]}else if(2===arguments.length)if("function"===
typeof arguments[1]){a=b=arguments[0];for(c=this.length;a<c;a+=1)this[a]=arguments[1](a)}else{a=b=arguments[1];for(c=this.length;a<c;a+=1)this[a]=arguments[0]}else if(3===arguments.length){if("function"===typeof arguments[2]){b=arguments[0];a=0;for(c=arguments[1];a<c;a+=1)this[a+b]=arguments[2](a+b)}else{b=arguments[1];a=0;for(c=arguments[2];a<c;a+=1)this[a+b]=arguments[0]}this.length<b+c&&(this.length=b+c)}else d.raise("TypeError","`fill': wrong number of arguments ("+arguments.length+" for 1..3)");
return this},find:function(a,b){1===arguments.length&&(b=a,a=null);for(var c=0,d=this.length;c<d;c+=1)if(b(this[c]))return this[c];return a},find_index:function(a){for(var b=0,c=this.length;b<c;b+=1)if(a(this[b]))return b;return null},first:function(a){if(0===arguments.length)return this[0];if("number"!==typeof a)d.raise("TypeError","`first': can't convert "+i(a)+" into Integer");else if(0>a)d.raise("ArgumentError","`first': negative array size");else return this.length<=a?this:d.Array["new"](h.Array.slice.call(this,
0,a))},flatten:function(a){var b=d.Array["new"]();0<arguments.length&&(a&&"number"!==typeof a)&&d.raise("TypeError","`flatten': can't convert "+i(a)+" into Integer");(function(c){for(var e=0,f=this.length;e<f;e+=1)"Array"===d.Object.prototype["class"].call(this[e])&&c!==a?arguments.callee.call(this[e],c+1):h.Array.push.call(b,this[e])}).call(this,0);return b},flat_map:function(a){var a=this.map(a),b=d.Array["new"](),c,e;for(c=0;e=a[c];c+=1)"Array"===i(e)?h.Array.push.apply(b,e):h.Array.push.call(b,
e);return b},include:function(a){for(var b=0,c=this.length;b<c;b+=1)if(d.Object.prototype.eql.call(this[b],a))return!0;return!1},index:function(a){var b,c=this.length;if("function"===typeof a)for(b=0;b<c;b+=1){if(a(this[b]))return b}else for(b=0;b<c;b+=1)if(this[b]===a)return b;return null},inject:function(){var a,b;if(0===arguments.length){if(0===this.length)return null;if(1===this.length)return this[0];a=this.shift()}1===arguments.length?a=this.shift():2===arguments.length&&(a=arguments[0]);b=arguments[arguments.length-
1];"function"!==typeof b&&d.raise("LocalJumpError","`each': no block given");for(var c=0,e=this.length;c<e;c+=1)a=b(a,this[c]);return a},insert:function(){var a,b,c,e;1>arguments.length&&d.raise("TypeError","`insert': wrong number of arguments ("+arguments.length+" for 1..2)");a=h.Array.slice.call(arguments);b=a.shift();"Number"!==i(b)&&d.raise("TypeError","`insert': can't convert "+i(b)+" into Integer");0>b&&(b+=this.length+1);if(this.length<b){c=0;for(e=b-this.length;c<e;c+=1)this.push(null)}a=
a.concat(h.Array.slice.call(this,b,this.length));h.Array.splice.call(this,b,this.length-b);return this.concat(a)},to_s:function(){var a=arguments.callee;return"["+h.Array.join.call(this.map(function(b){switch(i(b)){case "RegExp":return b.toString();case "Array":return a.call(b)}return JSON.stringify(b)}),", ")+"]"},keep_if:function(a){for(var b=[],c=0,d=this.length;c<d;c+=1)a(this[c])||b.push(c);for(a=b.length;a--;)h.Array.splice.call(this,b[a],1);return this},last:function(a){if(0===arguments.length)return 0===
this.length?null:this[this.length-1];this.length<a?a=this.length:0>a&&d.raise("ArgumentError","negative array size");return d.Array["new"](h.Array.slice.call(this,this.length-a))},pop:function(a){var b=d.Array["new"]();if(0===this.length)return 0===arguments.length?null:b;if(0===arguments.length)return h.Array.pop.call(this);if(this.length<a)a=this.length;else if(0>a)throw new TypeError("negative array size");return b.concat(h.Array.splice.call(this,this.length-a,a))},product:function(){var a=d.Array["new"](),
b=h.Array.slice.call(arguments),c="function"===typeof b[b.length-1]?b.pop():null,e,f;b.unshift(this.to_a());e=0;for(f=this.length;e<f;e+=1)(function(c,e){var f,h,n;if(b.length===c){n=d.Array["new"]();f=0;for(h=b.length;f<h;f+=1)n.push(b[f][e[f]]);a.push(n)}else{"Array"!==i(b[c])&&d.raise("TypeError","`product': can't convert "+i(b[c])+" into Array");f=0;for(h=b[c].length;f<h;f+=1)e[c]=f,arguments.callee(c+1,e)}})(1,[e]);if(c){e=0;for(f=a.length;e<f;e+=1)c(a[e]);return this}return a},push:function(){h.Array.push.apply(this,
arguments);return this},rassoc:function(a){for(var b=0,c=this.length;b<c;b+=1){var e=this[b];if(d.Object.prototype.eql.call(e[1],a))return e}return null},repeated_combination:function(a,b){var c=d.Array["new"](),e=this.length,f=[],g,h;if("number"!==typeof a)d.raise("TypeError","`repeated_combination': can't convert "+i(a)+" into Array");else{if(0>a)return c;if(0===a)return d.Array["new"]([c])}for(g=0;g<a;g+=1)f.push(this);(function(b,g,h){for(var i=b;i<e;i+=1)if(h[g]=i,g+1===a){for(var k=d.Array["new"](),
j=0;j<a;j+=1)k.push(f[j][h[j]]);c.push(k)}else arguments.callee(i,g+1,h)})(0,0,[]);if("function"===typeof b){g=0;for(h=c.length;g<h;g+=1)b(c[g]);return this}return c},repeated_permutation:function(a,b){var c=d.Array["new"](),e=this.length,f=[],g,k;if("number"!==typeof a)d.raise("TypeError","`repeated_permutation': can't convert "+i(a)+" into Array");else{if(0>a)return c;if(0===a)return d.Array["new"]([c])}for(g=0;g<a;g+=1)h.Array.push.call(f,this);(function(b,g){for(var i=0;i<e;i+=1)if(g[b]=i,b+1===
a){for(var k=d.Array["new"](),j=0;j<a;j+=1)h.Array.push.call(k,f[j][g[j]]);h.Array.push.call(c,k)}else arguments.callee(b+1,g)})(0,[]);if("function"===typeof b){g=0;for(k=c.length;g<k;g+=1)b(c[g]);return this}return c},replace:function(a){if("Array"!==i(a))try{a=a.to_ary()}catch(b){d.raise("TypeError","`replace': can't convert "+i(a)+" into Array")}this.clear();h.Array.push.apply(this,a);return this},reverse:function(){return h.Array.reverse.call(this.clone())},reverse_each:function(a){for(var b=
this.length;b--;)a(this[b]);return this},rindex:function(a){var b=this.length;if("function"===typeof a)for(;b--;){if(a(this[b]))return b}else for(;b--;)if(this[b]===a)return b;return null},rotate:function(a){if(0===arguments.length)a=1;else try{a=d.Number.prototype.to_int.call(a)}catch(b){d.raise("TypeError","`rotate': can't convert "+i(a)+" into Integer")}var c=h.Array.slice.call(this,0,a),e=h.Array.slice.call(this,a,this.length);return d.Array["new"]().concat(e).concat(c)},sample:function(a){var b=
this.length,c,e;if(0===arguments.length)return 0===b?null:this[Math.floor(Math.random()*b)];try{a=d.Number.prototype.to_int.call(a)}catch(f){d.raise("TypeError","`sample': can't convert "+i(a)+" into Integer")}0>a&&d.raise("ArgumentError","`sample': negative array size");c=d.Array["new"]();if(0===b)return c;for(b=this.clone();0<a--;)e=Math.floor(Math.random()*b.length),h.Array.push.call(c,h.Array.splice.call(b,e,1)[0]);return c},select:function(a){for(var b=[],c=0,d=this.length;c<d;c+=1)a(this[c])||
b.push(c);a=b.length;if(0===a)return null;for(;a--;)h.Array.splice.call(this,b[a],1);return this},shift:function(a){var b=this.length;if(0===arguments.length)return 0===b?null:h.Array.splice.call(this,0,1)[0];try{a=d.Number.prototype.to_int.call(a)}catch(c){d.raise("`shift': can't convert "+i(a)+" into Integer")}0>a&&d.raise("ArgumentError","`shift': negative array size");b<=a&&(a=b);return d.Array["new"](h.Array.splice.call(this,0,a))},shuffle:function(){var a=this.length,b,c,e;b=d.Array["new"]();
if(0===a)return b;for(c=this.clone();0<a--;)e=Math.floor(Math.random()*c.length),h.Array.push.call(b,h.Array.splice.call(c,e,1)[0]);return b},slice:function(){if(1===arguments.length)return this.at(arguments[0]);if(2===arguments.length){try{var a=d.Number.prototype.to_int.call(arguments[0])}catch(b){d.raise("TypeError","`slice': can't convert "+i(a)+" into Integer")}try{var c=d.Number.prototype.to_int.call(arguments[1])}catch(e){d.raise("TypeError","`slice': can't convert "+i(c)+" into Integer")}0>
a&&(a+=this.length);return this.length<=a||0>c?null:d.Array["new"](h.Array.slice.call(this,a,a+c))}d.raise("ArgumentError","`slice': wrong number of arguments ("+arguments.legnth+" for 1..2)")},sort_by:function(a){return this.map(function(b){return[a(b),b]}).sort(function(a,c){return a[0]<c[0]?-1:a[0]>c[0]?1:0}).map(function(a){return a[1]})},to_a:function(){return d.is_defined?this:h.Array.slice.call(this)},to_ary:function(){return this},transpose:function(){var a=d.Array["new"]();if(0===this.length)return a;
"Array"!==i(this[0])&&d.raise("TypeError","`transpose': can't convert "+i(this[0])+" into Array");for(var b=this[0].length,c=this.length,e=0;e<b;e+=1){for(var f=d.Array["new"](),g=0;g<c;g+=1)0===e&&("Array"!==i(this[g])&&d.raise("TypeError","`transpose': can't convert "+i(this[g])+" into Array"),this[g].length!==b&&d.raise("IndexError","transpose': element size differs ("+this[g].length+" should be "+b+")")),f.push(this[g][e]);a.push(f)}return a},uniq:function(a){var b,c,e,f,g;b=d.Array["new"]();
if("function"===typeof a){c=d.Array["new"]();f=0;for(g=this.length;f<g;f+=1)e=a(this[f]),c.include(e)||(h.Array.push.call(c,e),h.Array.push.call(b,this[f]))}else{f=0;for(g=this.length;f<g;f+=1)b.include(this[f])||h.Array.push.call(b,this[f])}return b},unshift:function(){h.Array.unshift.apply(this,arguments);return this},values_at:function(){var a,b,c,e;a=d.Array["new"]();b=0;for(c=arguments.length;b<c;b+=1){try{e=d.Number.prototype.to_int.call(arguments[b])}catch(f){d.raise("TypeError","`values_at': can't convert "+
i(e)+" into Integer")}0>e&&(e+=this.length);h.Array.push.call(a,void 0===this[e]?null:this[e])}return a},zip:function(){var a,b,c,e,f,g,i,j,l;a=d.Array["new"]();b=h.Array.slice.call(arguments);c="function"===typeof b[b.length-1]?b.pop():null;f=0;for(g=this.length;f<g;f+=1){e=d.Array["new"]();h.Array.push.call(e,this[f]);i=0;for(j=b.length;i<j;i+=1)l=b[i][f],void 0===l&&(l=null),h.Array.push.call(e,l);h.Array.push.call(a,e)}if("function"===typeof c){for(f=0;f<g;f+=1)c(a[f]);return null}return a}});
d.Array.prototype.entries=d.Array.prototype.to_a;d.Array.prototype.find_all=d.Array.prototype.select;d.Array.prototype.dup=d.Array.prototype.clone;d.Array.prototype.map=d.Array.prototype.collect;d.Array.prototype.detect=d.Array.prototype.find;d.Array.prototype.collect_concat=d.Array.prototype.flat_map;d.Array.prototype.inspect=d.Array.prototype.to_s;d.Array.prototype.permutation=d.Array.prototype.combination;d.Hash=function(a){if("object"===typeof a)for(var b in a)a.hasOwnProperty(b)&&(this[b]="[object Object]"===
Object.prototype.toString.call(a[b])?d.Hash["new"](a[b]):a[b]);return this};d.Hash["new"]=function(a){return new d.Hash(a)};d.Hash.prototype.to_a=function(){var a,b,c;c=[];for(a in this)this.hasOwnProperty(a)&&(b=this[a],c.push([a,b]));return c};d.Hash.prototype.to_hash=function(){return d.Hash["new"](this)};d.Hash.prototype.first=function(){return this.to_a()[0]};d.Hash.prototype.shift=function(){var a=this.first();delete this[a[0]];return a};d.Hash.prototype.each=function(a){var b=[];if("function"===
typeof a){if(1===a.length)this.to_a().each(a);else for(var c in this)if(this.hasOwnProperty(c)){var d=this[c];a(c,d)}return this}for(c in this)this.hasOwnProperty(c)&&(d=this[c],b.push(c,d));return b};d.Hash.prototype.each_key=function(a){var b=[];if("function"===typeof a){for(var c in this)this.hasOwnProperty(c)&&a(c);return this}for(c in this)this.hasOwnProperty(c)&&b.push(c);return b};d.Hash.prototype.inject=function(){var a,b;1===arguments.length?(a=this.to_a()[0],this.shift()):2===arguments.length&&
(a=arguments[0]);b=arguments[arguments.length-1];this.each(function(c){a=b(a,c)});return a};d.Hash.prototype.length=function(){var a=0,b;for(b in this)this.hasOwnProperty(b)&&(a+=1);return a};d.Hash.prototype.size=d.Hash.prototype.length;d.Hash.prototype.keys=function(){return Object.keys(this)};d.Hash.prototype.key=function(a){for(var b in this)if(this.hasOwnProperty(b)&&(this[b]===a||d.Hash.prototype.eql.call(this[b],a)))return b;return null};d.Hash.prototype.merge=function(a,b){var c,e;c=d.Hash["new"](this);
try{!a instanceof Object&&(a=a.to_hash())}catch(f){d.raise("TypeError","'merge`: can't convert "+i(a)+" into Hash")}if(1===arguments.length)for(e in a)a.hasOwnProperty(e)&&(c[e]=a[e]);else for(e in a)a.hasOwnProperty(e)&&(c[e]=b(e,c[e],a[e]));return c};d.String=function(){};d.String["new"]=function(a){0===arguments.length&&(a="");if("string"===typeof a)return a;d.raise("TypeError","can't convert "+i(a)+" into String")};d.String.prototype.sub=function(a,b){return"[object Object]"===Object.prototype.toString.call(b)?
this.replace(a,function(a){return b[a]||""}):this.replace(a,b)};d.String.prototype.gsub=function(a,b){a=a.toString().replace(/\/(.*)\/.*$/,"$1");a=RegExp(a,"g");return d.String.prototype.sub.call(this,a,b)};d.String.prototype.chop=function(){return/\r\n$/.test(this)?this.replace(/\r\n$/,""):this.slice(0,this.length-1)};d.String.prototype.chomp=function(a){var b;if(0===arguments.length)return this.replace(/\r$|\n$/,"");if("string"===typeof a)return b=RegExp(a+"$"),this.replace(b,"");if(null==a)return this.valueOf();
d.raise("TypeError","`chomp': can't convert "+i(a)+" into String")};d.String.prototype.each_char=function(a){var b=[];if("function"===typeof a){for(var c=0,d=this.length;c<d;c+=1)a(this.charAt(c));return this.valueOf()}c=0;for(d=this.length;c<d;c+=1)b.push(this.charAt(c));return b};d.String.prototype.chars=d.String.prototype.each_char;d.String.prototype.clear=function(){return""};d.String.prototype.clone=function(){return this.toString()};d.String.prototype.match=function(a,b){1===arguments.length&&
(b=0);var c=this.slice(b,this.length)._match(a);return null!==c?c.slice(1,c.length):null};d.String.prototype.insert=function(a,b){return this.slice(0,a)+b+this.slice(a,this.length)};d.String.prototype.empty=function(){return""===this.valueOf()};d.String.prototype.index=function(a,b){var b=b||0,c=this.slice(b,this.length),d=0<=b?b:this.length+b,f;"string"===typeof a?f=this.indexOf(a,d):"number"===typeof a?f=this.indexOf(String.fromCharCode(a),d):a instanceof RegExp&&(f=c.search(a)+d);return-1===f?
null:void 0!==f?f:null};d.String.prototype.to_s=function(){return this};d.Number=function(){};d.Number.prototype.to_s=function(){return this+""};d.Number.prototype.to_int=function(){"number"!==typeof this.valueOf()&&d.raise("TypeError","`to_int': can't convert "+i(this.valueOf())+" into Integer");return Math.floor(this)};d.Number.prototype.inspect=function(){return this.to_s()};d.Number.prototype.times=function(a){var b,c,d;b=[];c=this.valueOf();if(0<=c){if("function"===typeof a){for(d=0;d<c;d+=1)a(d);
return c}for(d=0;d<c;d+=1)b.push(d);return b}};d.Number.prototype.upto=function(a,b){if(0===arguments.length)throw new TypeError("`upto': wrong number of arguments (0 for 1..2)");return this.step(a,1,b)};d.Number.prototype.downto=function(a,b){if(0===arguments.length)throw new TypeError("`downto': wrong number of arguments (0 for 1..2)");return this.step(a,-1,b)};d.Number.prototype.step=function(a,b,c){var d,f,g;d=[];f=this.valueOf();if(0===arguments.length)throw new TypeError("`step': wrong number of arguments (0 for 1..2)");
1===arguments.length?b=1:"function"===typeof b&&(c=b,b=1);if(0<b){if("function"===typeof c){for(g=f;g<=a;g+=b)c(g);return f}for(g=f;g<=a;g+=b)d.push(g);return d}if("function"===typeof c){for(g=f;a<=g;g+=b)c(g);return f}for(g=f;a<=g;g+=b)d.push(g);return d};d.Number.prototype.gcd=function(a){var b,c;b=Math.abs(this.valueOf());c=Math.abs(a);if(0!==Math.floor(b)-b||0!==Math.floor(c)-c)throw new TypeError("`gcd' not an integer");a=c<b?b:c;b=c<b?c:b;return 0===b?a:b.gcd(a%b)};d.Number.prototype.real=function(){return this.valueOf()};
d.Number.prototype.next=function(){var a=this.valueOf();if(0!==Math.floor(a)-a)throw new TypeError("`next' not an integer");return a+1};d.Number.prototype.div=function(a){return Math.floor(this/a)};this.Rubylike=d}).call(this);
