// Rubylike.js (https://github.com/ksss/Rubylike.js)
// Copyright (c) 2012 ksss <co000ri@gmail.com>
(function(){var c=function(a){if("function"!==typeof a)throw new TypeError("arguments must be a function");c.define();a=a(c);c.remove();return a},l=Array.prototype.slice,q=Array.prototype.sort,j=Array.prototype.splice,r=Array.prototype.unshift,s=Array.prototype.pop,i=Array.prototype.push,t=Array.prototype.join;c.Object=function(){};c.Object["new"]=function(){return new c.Object};c.Object.prototype["class"]=function(){if(null===this)return"nil";if(void 0===this)return"undefined";var a=this.constructor;
return"function"===typeof a?(""+a).replace(/^\s*function\s*([^\(]*)[\S\s]+$/im,"$1"):a};c.Object.prototype.eql=function(a){var b,d;if(this===a)return!0;if(this.prototype!==a.prototype)return!1;if(this.valueOf()===a.valueOf())return!0;if(this instanceof Date&&a instanceof Date)return this.getTime()===a.getTime();if("object"!=typeof this&&"object"!=typeof a)return this===a;try{d=Object.keys(this),b=Object.keys(a)}catch(c){return!1}if(d.length!==b.length)return!1;q.call(d);q.call(b);for(var f=0,g=d.length;f<
g;f+=1)if(d[f]!==b[f])return!1;for(f=d.length-1;0<=f;f--)if(b=d[f],!arguments.callee.call(this[b],a[b]))return!1;return!0};c.Object.prototype.methods=function(){return c[this["class"]()]._methods};c.Array=function(){this.length=0};c.Array["new"]=function(a,b){var d=c.is_defined?[]:new c.Array;if(0===arguments.length)return d;switch(h(a)){case "Number":void 0===b&&(b=null);for(var e=0;e<a;e+=1)i.call(d,b);break;case "Array":d.concat(a);break;case "undefined":break;case "nil":c.raise("TypeError","`initialize': no implicit conversion from nil to integer");
break;default:c.raise("TypeError","`initialize': can't convert "+h(a)+" into Integer")}return d};c.Array.prototype=[];c.Array.prototype.methods=function(){return Object.keys(c.Array.prototype)};c.Array.prototype.assoc=function(a){for(var b=0,d=this.length;b<d;b+=1){var e=this[b];if(c.Object.prototype.eql.call(e[0],a))return e}return null};c.Array.prototype.at=function(a){try{a=c.Number.prototype.to_int.call(a)}catch(b){c.raise("TypeError","`at': can't convert "+h(a)+" into Integer")}0>a&&(a+=this.length);
a=this[a];return void 0===a?null:a};c.Array.prototype.clear=function(){j.call(this,0,this.length);return this};c.Array.prototype.clone=function(){return this.map(function(a){return a})};c.Array.prototype.dup=c.Array.prototype.clone;c.Array.prototype.collect=function(a){for(var b=c.Array["new"](),d=0,e=this.length;d<e;d+=1)i.call(b,a(this[d]));return b};c.Array.prototype.map=c.Array.prototype.collect;c.Array.prototype.combination=function(a,b){(0===arguments.length||2<arguments.length)&&c.raise("TypeError",
"`combination': wrong number of arguments ("+arguments.length+" for 1)");"number"!==typeof a&&c.raise("TypeError","`combination': can't convert "+h(a)+" into Integer");var d;a:{d=c.Array["new"]();var e=this.length;if(!(0>a||e<a))if(0===a)d.push([]);else if(1===a)for(var f=0;f<e;f+=1)i.call(d,[this[f]]);else{for(var g=0,k=[],n=[],f=0;f<a+1;f+=1)n.push(0);for(n[0]=-1;;){k[g]=this[n[g+1]];for(g++;g<a;g++)n[g+1]=n[g]+1,k[g]=this[n[g+1]];i.call(d,c.Array.prototype.clone.call(k));do{if(0===g)break a;n[g--]++}while(n[g+
1]+a===e+g+1)}}}if("function"===typeof b){e=0;for(f=d.length;e<f;e+=1)b(d[e]);return this}return d};c.Array.prototype.compact=function(){return this.reject(function(a){return null===a})};c.Array.prototype.concat=function(a){"Array"!==h(a)&&c.raise("TypeError","`concat': can't convert "+h(a)+" into Array");"function"===typeof a.to_a?i.apply(this,a.to_a()):i.apply(this,a);return this};c.Array.prototype.reject=function(a){for(var b=c.Array["new"](),d=0,e=this.length;d<e;d+=1)a(this[d])||i.call(b,this[d]);
return b.length===this.length?null:b};c.Array.prototype.delete_if=function(a){for(var b=0,d=this.length;b<d;b+=1)a(this[b])&&j.call(this,b,1);return this};c.Array.prototype.cycle=function(a,b){if(2!==arguments.length)c.raise("TypeError","`cycle': wrong number of arguments ("+arguments.length+" for 2)");else for(var d=0,e=this.length;d<a;d+=1)b(this[d%e]);return null};c.Array.prototype["delete"]=function(a,b){var d,c=this.length,f=[];if("function"===typeof b)for(d=0;d<c;d+=1)this[d]===a?f.push(d):
b(this[d]);else for(d=0;d<c;d+=1)this[d]===a&&f.push(d);for(d=f.length;d--;)j.call(this,f[d],1);return c!==this.length?a:null};c.Array.prototype.delete_at=function(a){0>a&&(a+=this.length);var b=this.at(a);null!==b&&j.call(this,a,1);return b};c.Array.prototype.each=function(a){for(var b=0,d=this.length;b<d;b+=1)a(this[b]);return this};c.Array.prototype.each_index=function(a){for(var b=0,d=this.length;b<d;b+=1)a(b);return this};c.Array.prototype.each_with_index=function(a){for(var b=0,d=this.length;b<
d;b+=1)a(this[b],b);return this};c.Array.prototype.eql=function(a){return c.Object.prototype.eql.call(this,a)};c.Array.prototype.fetch=function(a,b){0===arguments.length&&c.raise("TypeError","`fetch': wrong number of arguments ("+arguments.length+" for 1..2)");var d=this.at(a);if(null===d){if(1===arguments.length)throw Error("`fetch': index "+a+" outside of array bounds: -"+this.length+"..."+this.length);return"function"===typeof b?b(a):b}return d};c.Array.prototype.fill=function(){var a,b,d;if(1===
arguments.length)if("function"===typeof arguments[0]){a=0;for(d=this.length;a<d;a+=1)this[a]=arguments[0](a)}else{a=0;for(d=this.length;a<d;a+=1)this[a]=arguments[0]}else if(2===arguments.length)if("function"===typeof arguments[1]){a=b=arguments[0];for(d=this.length;a<d;a+=1)this[a]=arguments[1](a)}else{a=b=arguments[1];for(d=this.length;a<d;a+=1)this[a]=arguments[0]}else if(3===arguments.length){if("function"===typeof arguments[2]){b=arguments[0];a=0;for(d=arguments[1];a<d;a+=1)this[a+b]=arguments[2](a+
b)}else{b=arguments[1];a=0;for(d=arguments[2];a<d;a+=1)this[a+b]=arguments[0]}this.length<b+d&&(this.length=b+d)}else c.raise("TypeError","`fill': wrong number of arguments ("+arguments.length+" for 1..3)");return this};c.Array.prototype.first=function(a){if(0===arguments.length)return this[0];if("number"!==typeof a)c.raise("TypeError","`first': can't convert "+h(a)+" into Integer");else if(0>a)c.raise("ArgumentError","`first': negative array size");else return this.length<=a?this:c.Array["new"](l.call(this,
0,a))};c.Array.prototype.flatten=function(a){var b=c.Array["new"]();0<arguments.length&&(a&&"number"!==typeof a)&&c.raise("TypeError","`flatten': can't convert "+h(a)+" into Integer");(function(d){for(var e=0,f=this.length;e<f;e+=1)"Array"===c.Object.prototype["class"].call(this[e])&&d!==a?arguments.callee.call(this[e],d+1):i.call(b,this[e])}).call(this,0);return b};c.Array.prototype.include=function(a){for(var b=0,d=this.length;b<d;b+=1)if(c.Object.prototype.eql.call(this[b],a))return!0;return!1};
c.Array.prototype.index=function(a){var b,d=this.length;if("function"===typeof a)for(b=0;b<d;b+=1){if(a(this[b]))return b}else for(b=0;b<d;b+=1)if(this[b]===a)return b;return null};c.Array.prototype.inject=function(){var a,b;if(0===arguments.length){if(0===this.length)return null;if(1===this.length)return this[0];a=this.shift()}1===arguments.length?a=this.shift():2===arguments.length&&(a=arguments[0]);b=arguments[arguments.length-1];"function"!==typeof b&&c.raise("LocalJumpError","`each': no block given");
for(var d=0,e=this.length;d<e;d+=1)a=b(a,this[d]);return a};c.Array.prototype.insert=function(){var a,b,d,e;1>arguments.length&&c.raise("TypeError","`insert': wrong number of arguments ("+arguments.length+" for 1..2)");a=l.call(arguments);b=a.shift();"Number"!==h(b)&&c.raise("TypeError","`insert': can't convert "+h(b)+" into Integer");0>b&&(b+=this.length+1);if(this.length<b){d=0;for(e=b-this.length;d<e;d+=1)this.push(null)}a=a.concat(l.call(this,b,this.length));j.call(this,b,this.length-b);return this.concat(a)};
c.Array.prototype.to_s=function(){return"["+t.call(this.map(function(a){switch(h(a)){case "RegExp":return a.toString();case "Array":return c.Array.prototype.to_s.call(a)}return JSON.stringify(a)}),", ")+"]"};c.Array.prototype.inspect=c.Array.prototype.to_s;c.Array.prototype.keep_if=function(a){for(var b=[],d=0,c=this.length;d<c;d+=1)a(this[d])||b.push(d);for(a=b.length;a--;)j.call(this,b[a],1);return this};c.Array.prototype.last=function(a){if(0===arguments.length)return 0===this.length?null:this[this.length-
1];this.length<a?a=this.length:0>a&&c.raise("ArgumentError","negative array size");return c.Array["new"](l.call(this,this.length-a))};c.Array.prototype.permutation=c.Array.prototype.combination;c.Array.prototype.pop=function(a){var b=c.Array["new"]();if(0===this.length)return 0===arguments.length?null:b;if(0===arguments.length)return s.call(this);if(this.length<a)a=this.length;else if(0>a)throw new TypeError("negative array size");return b.concat(j.call(this,this.length-a,a))};c.Array.prototype.product=
function(){var a=c.Array["new"](),b=l.call(arguments),d="function"===typeof b[b.length-1]?b.pop():null,e,f;b.unshift(this.to_a());e=0;for(f=this.length;e<f;e+=1)(function(d,e){var f,i,j;if(b.length===d){j=c.Array["new"]();f=0;for(i=b.length;f<i;f+=1)j.push(b[f][e[f]]);a.push(j)}else{"Array"!==h(b[d])&&c.raise("TypeError","`product': can't convert "+h(b[d])+" into Array");f=0;for(i=b[d].length;f<i;f+=1)e[d]=f,arguments.callee(d+1,e)}})(1,[e]);if(d){e=0;for(f=a.length;e<f;e+=1)d(a[e]);return this}return a};
c.Array.prototype.push=function(){i.apply(this,arguments);return this};c.Array.prototype.rassoc=function(a){for(var b=0,d=this.length;b<d;b+=1){var e=this[b];if(c.Object.prototype.eql.call(e[1],a))return e}return null};c.Array.prototype.repeated_combination=function(a,b){var d=c.Array["new"](),e=this.length,f=[],g,i;if("number"!==typeof a)c.raise("TypeError","`repeated_combination': can't convert "+h(a)+" into Array");else{if(0>a)return d;if(0===a)return c.Array["new"]([d])}for(g=0;g<a;g+=1)f.push(this);
(function(b,g,h){for(var i=b;i<e;i+=1)if(h[g]=i,g+1===a){for(var j=c.Array["new"](),k=0;k<a;k+=1)j.push(f[k][h[k]]);d.push(j)}else arguments.callee(i,g+1,h)})(0,0,[]);if("function"===typeof b){g=0;for(i=d.length;g<i;g+=1)b(d[g]);return this}return d};c.Array.prototype.repeated_permutation=function(a,b){var d=c.Array["new"](),e=this.length,f=[],g,j;if("number"!==typeof a)c.raise("TypeError","`repeated_permutation': can't convert "+h(a)+" into Array");else{if(0>a)return d;if(0===a)return c.Array["new"]([d])}for(g=
0;g<a;g+=1)i.call(f,this);(function(b,g){for(var h=0;h<e;h+=1)if(g[b]=h,b+1===a){for(var j=c.Array["new"](),k=0;k<a;k+=1)i.call(j,f[k][g[k]]);i.call(d,j)}else arguments.callee(b+1,g)})(0,[]);if("function"===typeof b){g=0;for(j=d.length;g<j;g+=1)b(d[g]);return this}return d};c.Array.prototype.replace=function(a){if("Array"!==h(a))try{a=a.to_ary()}catch(b){c.raise("TypeError","`replace': can't convert "+h(a)+" into Array")}this.clear();i.apply(this,a);return this};c.Array.prototype.reverse=function(){for(var a=
c.Array["new"](),b=this.length;b--;)a.push(this[b]);return a};c.Array.prototype.reverse_each=function(a){for(var b=this.length;b--;)a(this[b]);return this};c.Array.prototype.rindex=function(a){var b=this.length;if("function"===typeof a)for(;b--;){if(a(this[b]))return b}else for(;b--;)if(this[b]===a)return b;return null};c.Array.prototype.rotate=function(a){if(0===arguments.length)a=1;else try{a=c.Number.prototype.to_int.call(a)}catch(b){c.raise("TypeError","`rotate': can't convert "+h(a)+" into Integer")}var d=
l.call(this,0,a),e=l.call(this,a,this.length);return c.Array["new"]().concat(e).concat(d)};c.Array.prototype.sample=function(a){var b=this.length,d,e;if(0===arguments.length)return 0===b?null:this[Math.floor(Math.random()*b)];try{a=c.Number.prototype.to_int.call(a)}catch(f){c.raise("TypeError","`sample': can't convert "+h(a)+" into Integer")}0>a&&c.raise("ArgumentError","`sample': negative array size");d=c.Array["new"]();if(0===b)return d;for(b=this.clone();0<a--;)e=Math.floor(Math.random()*b.length),
i.call(d,j.call(b,e,1)[0]);return d};c.Array.prototype.select=function(a){for(var b=[],d=0,c=this.length;d<c;d+=1)a(this[d])||b.push(d);a=b.length;if(0===a)return null;for(;a--;)j.call(this,b[a],1);return this};c.Array.prototype.shift=function(a){var b=this.length;if(0===arguments.length)return 0===b?null:j.call(this,0,1)[0];try{a=c.Number.prototype.to_int.call(a)}catch(d){c.raise("`shift': can't convert "+h(a)+" into Integer")}0>a&&c.raise("ArgumentError","`shift': negative array size");b<=a&&(a=
b);return c.Array["new"](j.call(this,0,a))};c.Array.prototype.shuffle=function(){var a=this.length,b,d,e;b=c.Array["new"]();if(0===a)return b;for(d=this.clone();0<a--;)e=Math.floor(Math.random()*d.length),i.call(b,j.call(d,e,1)[0]);return b};c.Array.prototype.slice=function(){if(1===arguments.length)return this.at(arguments[0]);if(2===arguments.length){var a=c.Number.prototype.to_int.call(arguments[0]),b=c.Number.prototype.to_int.call(arguments[1]);0>a&&(a+=this.length);return this.length<=a||0>b?
null:c.Array["new"](l.call(this,a,b))}c.raise("ArgumentError","`slice': wrong number of arguments ("+arguments.legnth+" for 1..2)")};c.Array.prototype.sort_by=function(a){return this.map(function(b){return[a(b),b]}).sort(function(a,d){return a[0]<d[0]?-1:a[0]>d[0]?1:0}).map(function(a){return a[1]})};c.Array.prototype.to_a=function(){return c.is_defined?this:l.call(this)};c.Array.prototype.to_ary=function(){return this};c.Array.prototype.transpose=function(){var a=c.Array["new"]();if(0===this.length)return a;
"Array"!==h(this[0])&&c.raise("TypeError","`transpose': can't convert "+h(this[0])+" into Array");for(var b=this[0].length,d=this.length,e=0;e<b;e+=1){for(var f=c.Array["new"](),g=0;g<d;g+=1)0===e&&("Array"!==h(this[g])&&c.raise("TypeError","`transpose': can't convert "+h(this[g])+" into Array"),this[g].length!==b&&c.raise("IndexError","transpose': element size differs ("+this[g].length+" should be "+b+")")),f.push(this[g][e]);a.push(f)}return a};c.Array.prototype.uniq=function(a){var b,d,e,f,g;b=
c.Array["new"]();if("function"===typeof a){d=c.Array["new"]();f=0;for(g=this.length;f<g;f+=1)e=a(this[f]),d.include(e)||(i.call(d,e),i.call(b,this[f]))}else{f=0;for(g=this.length;f<g;f+=1)b.include(this[f])||i.call(b,this[f])}return b};c.Array.prototype.unshift=function(){r.apply(this,arguments);return this};c.Array.prototype.values_at=function(){var a,b,d,e;a=c.Array["new"]();b=0;for(d=arguments.length;b<d;b+=1){try{e=c.Number.prototype.to_int.call(arguments[b])}catch(f){c.raise("TypeError","`values_at': can't convert "+
h(e)+" into Integer")}0>e&&(e+=this.length);i.call(a,void 0===this[e]?null:this[e])}return a};c.Array.prototype.zip=function(){var a,b,d,e,f,g,h,j,m;a=c.Array["new"]();b=l.call(arguments);d="function"===typeof b[b.length-1]?b.pop():null;f=0;for(g=this.length;f<g;f+=1){e=c.Array["new"]();i.call(e,this[f]);h=0;for(j=b.length;h<j;h+=1)m=b[h][f],void 0===m&&(m=null),i.call(e,m);i.call(a,e)}if("function"===typeof d){for(f=0;f<g;f+=1)d(a[f]);return null}return a};c.Hash=function(a){if("object"===typeof a)for(var b in a)a.hasOwnProperty(b)&&
(this[b]="[object Object]"===Object.prototype.toString.call(a[b])?c.Hash["new"](a[b]):a[b]);return this};c.Hash["new"]=function(a){return new c.Hash(a)};c.Hash.prototype.to_a=function(){var a,b,d;d=[];for(a in this)this.hasOwnProperty(a)&&(b=this[a],d.push([a,b]));return d};c.Hash.prototype.to_hash=function(){return c.Hash["new"](this)};c.Hash.prototype.first=function(){return this.to_a()[0]};c.Hash.prototype.shift=function(){var a=this.first();delete this[a[0]];return a};c.Hash.prototype.each=function(a){var b=
[];if("function"===typeof a){if(1===a.length)this.to_a().each(a);else for(var d in this)if(this.hasOwnProperty(d)){var c=this[d];a(d,c)}return this}for(d in this)this.hasOwnProperty(d)&&(c=this[d],b.push(d,c));return b};c.Hash.prototype.each_key=function(a){var b=[];if("function"===typeof a){for(var d in this)this.hasOwnProperty(d)&&a(d);return this}for(d in this)this.hasOwnProperty(d)&&b.push(d);return b};c.Hash.prototype.inject=function(){var a,b;1===arguments.length?(a=this.to_a()[0],this.shift()):
2===arguments.length&&(a=arguments[0]);b=arguments[arguments.length-1];this.each(function(d){a=b(a,d)});return a};c.Hash.prototype.length=function(){var a=0,b;for(b in this)this.hasOwnProperty(b)&&(a+=1);return a};c.Hash.prototype.size=c.Hash.prototype.length;c.Hash.prototype.keys=function(){return Object.keys(this)};c.Hash.prototype.key=function(a){for(var b in this)if(this.hasOwnProperty(b)&&(this[b]===a||c.Hash.prototype.eql.call(this[b],a)))return b;return null};c.Hash.prototype.merge=function(a,
b){var d,e;d=c.Hash["new"](this);try{!a instanceof Object&&(a=a.to_hash())}catch(f){c.raise("TypeError","'merge`: can't convert "+h(a)+" into Hash")}if(1===arguments.length)for(e in a)a.hasOwnProperty(e)&&(d[e]=a[e]);else for(e in a)a.hasOwnProperty(e)&&(d[e]=b(e,d[e],a[e]));return d};c.String=function(){};c.String["new"]=function(a){0===arguments.length&&(a="");if("string"===typeof a)return a;c.raise("TypeError","can't convert "+h(a)+" into String")};c.String.prototype.sub=function(a,b){return"[object Object]"===
Object.prototype.toString.call(b)?this.replace(a,function(a){return b[a]||""}):this.replace(a,b)};c.String.prototype.gsub=function(a,b){a=a.toString().replace(/\/(.*)\/.*$/,"$1");a=RegExp(a,"g");return c.String.prototype.sub.call(this,a,b)};c.String.prototype.chop=function(){return/\r\n$/.test(this)?this.replace(/\r\n$/,""):this.slice(0,this.length-1)};c.String.prototype.chomp=function(a){var b;if(0===arguments.length)return this.replace(/\r$|\n$/,"");if("string"===typeof a)return b=RegExp(a+"$"),
this.replace(b,"");if(null==a)return this.valueOf();c.raise("TypeError","`chomp': can't convert "+h(a)+" into String")};c.String.prototype.each_char=function(a){var b=[];if("function"===typeof a){for(var d=0,c=this.length;d<c;d+=1)a(this.charAt(d));return this.valueOf()}d=0;for(c=this.length;d<c;d+=1)b.push(this.charAt(d));return b};c.String.prototype.chars=c.String.prototype.each_char;c.String.prototype.clear=function(){return""};c.String.prototype.clone=function(){return this.toString()};c.String.prototype.match=
function(a,b){1===arguments.length&&(b=0);var d=this.slice(b,this.length)._match(a);return null!==d?d.slice(1,d.length):null};c.String.prototype.insert=function(a,b){return this.slice(0,a)+b+this.slice(a,this.length)};c.String.prototype.empty=function(){return""===this.valueOf()};c.String.prototype.index=function(a,b){var b=b||0,d=this.slice(b,this.length),c=0<=b?b:this.length+b,f;"string"===typeof a?f=this.indexOf(a,c):"number"===typeof a?f=this.indexOf(String.fromCharCode(a),c):a instanceof RegExp&&
(f=d.search(a)+c);return-1===f?null:void 0!==f?f:null};c.String.prototype.to_s=function(){return this};c.Number=function(){};c.Number.prototype.to_s=function(){return this+""};c.Number.prototype.to_int=function(){"number"!==typeof this.valueOf()&&c.raise("TypeError","`to_int': can't convert "+h(this.valueOf())+" into Integer");return Math.floor(this)};c.Number.prototype.inspect=function(){return this.to_s()};c.Number.prototype.times=function(a){var b,d,c;b=[];d=this.valueOf();if(0<=d){if("function"===
typeof a){for(c=0;c<d;c+=1)a(c);return d}for(c=0;c<d;c+=1)b.push(c);return b}};c.Number.prototype.upto=function(a,b){if(0===arguments.length)throw new TypeError("`upto': wrong number of arguments (0 for 1..2)");return this.step(a,1,b)};c.Number.prototype.downto=function(a,b){if(0===arguments.length)throw new TypeError("`downto': wrong number of arguments (0 for 1..2)");return this.step(a,-1,b)};c.Number.prototype.step=function(a,b,c){var e,f,g;e=[];f=this.valueOf();if(0===arguments.length)throw new TypeError("`step': wrong number of arguments (0 for 1..2)");
1===arguments.length?b=1:"function"===typeof b&&(c=b,b=1);if(0<b){if("function"===typeof c){for(g=f;g<=a;g+=b)c(g);return f}for(g=f;g<=a;g+=b)e.push(g);return e}if("function"===typeof c){for(g=f;a<=g;g+=b)c(g);return f}for(g=f;a<=g;g+=b)e.push(g);return e};c.Number.prototype.gcd=function(a){var b,c;b=Math.abs(this.valueOf());c=Math.abs(a);if(0!==Math.floor(b)-b||0!==Math.floor(c)-c)throw new TypeError("`gcd' not an integer");a=c<b?b:c;b=c<b?c:b;return 0===b?a:b.gcd(a%b)};c.Number.prototype.real=function(){return this.valueOf()};
c.Number.prototype.next=function(){var a=this.valueOf();if(0!==Math.floor(a)-a)throw new TypeError("`next' not an integer");return a+1};c.Number.prototype.div=function(a){return Math.floor(this/a)};var h=function(a){if(null===a)return"nil";if(void 0===a)return"undefined";switch(Object.prototype.toString.call(a)){case "[object Number]":return"Number"}var b=/^\s*function\s*([^\(]*)[\S\s]+$/im;return"function"===typeof a?(a+"").replace(b,"$1"):(a.constructor+"").replace(b,"$1")},m=function(a,b){void 0===
c[h(a)]._methods&&(c[h(a)]._methods=[]);a["new"]=b["new"];for(var d in b.prototype)b.prototype.hasOwnProperty(d)&&(c[h(a)]._methods.push(d),"function"===typeof a.prototype[d]&&"Hash"!==h(a)&&(a.prototype["_"+d]=a.prototype[d],c[h(a)]._methods.push("_"+d)),a.prototype[d]=b.prototype[d])},p=function(a){var b=q.call(c[h(a)]._methods).reverse();c[h(a)]._methods=[];delete a["new"];for(var d=0,e=b.length;d<e;d+=1){var f=b[d];/^_/.test(f)&&"_methods"!==f&&(a.prototype[f.substr(1,f.length-1)]=a.prototype[f]);
delete a.prototype[f]}};c.version="0.0.0";c.is_defined=!1;c.define=function(){nil=null;Hash=c.Hash;m(Object,c.Object);m(Array,c.Array);m(Hash,c.Hash);m(String,c.String);m(Number,c.Number);c.is_defined=!0};c.remove=function(){p(Object);p(Array);p(String);p(Number);delete Hash;delete nil;c.is_defined=!1};c.raise=function(a,b){var c=Error();c.name=a;c.message=b;throw c;};this.Rubylike=c}).call(this);
